const styles = {
  app: {
    minHeight: "100vh",
    background: "linear-gradient(160deg, #dde8ec 0%, #d8d8d8 100%)",
    fontFamily: "'Segoe UI', 'Helvetica Neue', sans-serif",
  },
  // ── Navbar ──────────────────────────────────
  navbar: {
    background: "#ffffff",
    color: "#1a1a1a",
    height: 70,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 28px",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 1px 8px rgba(0,0,0,0.07)",
    borderBottom: "1px solid #ebebeb",
  },
  logo: { display: "flex", alignItems: "center" },
  logoImg: { height: 52, objectFit: "contain" },
  navActions: { display: "flex", alignItems: "center", gap: 6 },
  iconBtn: {
    background: "none", border: "none", color: "#555",
    cursor: "pointer", padding: 7, display: "flex", alignItems: "center",
    borderRadius: 8, transition: "background 0.15s",
  },
  divider: { width: 1, height: 28, background: "#e4e4e4", margin: "0 8px" },
  accountLabel: { fontSize: 13, color: "#666", fontWeight: 500 },
  avatarCircle: {
    width: 36, height: 36, borderRadius: "50%",
    background: "linear-gradient(135deg, #667eea, #764ba2)",
    display: "flex", alignItems: "center", justifyContent: "center",
    color: "#fff", cursor: "pointer", marginLeft: 4,
    boxShadow: "0 2px 8px rgba(102,126,234,0.4)",
  },
  // ── Navbar New Button ────────────────────────
  navNewBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#2bbdcc",
    color: "#fff",
    border: "none",
    borderRadius: 9,
    padding: "8px 18px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 10px rgba(43,189,204,0.35)",
    transition: "background 0.15s, box-shadow 0.15s, transform 0.15s",
    letterSpacing: "-0.1px",
  },
  navNewBtnHover: {
    background: "#22aaba",
    boxShadow: "0 4px 16px rgba(43,189,204,0.45)",
    transform: "translateY(-1px)",
  },
  // ── Layout ──────────────────────────────────
  main: { flex: 1, padding: "28px 36px" },
  contentCard: {
    background: "rgba(235,235,235,0.85)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    borderRadius: 16,
    padding: "32px 36px",
    minHeight: 600,
    boxShadow: "0 4px 24px rgba(0,0,0,0.06)",
    border: "1px solid rgba(255,255,255,0.7)",
  },
  // ── Section ─────────────────────────────────
  section: { marginBottom: 36 },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
    maxWidth: 800,
  },
  sectionToggle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 8px 4px 4px",
    borderRadius: 8,
    transition: "background 0.15s",
    outline: "none",
  },
  sectionTitleText: {
    fontSize: 20,
    fontWeight: 700,
    color: "#1a1a1a",
    letterSpacing: "-0.3px",
    userSelect: "none",
  },
  chevronIcon: {
    fontSize: 11,
    color: "#999",
    transition: "transform 0.2s ease",
    display: "inline-block",
    lineHeight: 1,
  },
  // ── See All Button ───────────────────────────
  seeAllBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    borderRadius: 7,
    padding: "5px 10px",
    fontSize: 13,
    color: "#888",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  seeAllBtnHover: {
    color: "#2bbdcc",
    background: "rgba(43,189,204,0.07)",
  },
  // ── Cards ───────────────────────────────────
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(270px, 1fr))",
    gap: 18,
    maxWidth: 800,
  },
  card: {
    background: "#fff",
    border: "1px solid #e2e2e2",
    borderRadius: 14,
    overflow: "hidden",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0,0,0,0.07)",
    transition: "box-shadow 0.2s ease, transform 0.2s ease",
  },
  cardHover: {
    boxShadow: "0 8px 24px rgba(0,0,0,0.13)",
    transform: "translateY(-3px)",
  },
  cardPreviewWrapper: {
    background: "#2bbdcc",
    padding: "16px 16px 0 16px",
    display: "flex",
    justifyContent: "center",
  },
  previewBox: {
    background: "#fff",
    borderRadius: "10px 10px 0 0",
    padding: "18px 20px",
    width: "100%",
  },
  previewInner: {
    display: "flex",
    gap: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  iconBox: {
    background: "#f4f4f4",
    borderRadius: 10,
    padding: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cardFooter: { padding: "14px 16px", display: "flex", alignItems: "flex-start", gap: 10 },
  cardTitleIcon: { marginTop: 2, color: "#555", flexShrink: 0 },
  cardTitle: { fontWeight: 600, fontSize: 14, color: "#1a1a1a", letterSpacing: "-0.1px" },
  cardPath: { fontSize: 12, color: "#999", marginTop: 3, fontWeight: 400 },
  // ── Workspace ───────────────────────────────
  workspaceItem: {
    background: "#fff",
    border: "1px solid #e2e2e2",
    borderRadius: 12,
    padding: "14px 18px",
    display: "flex",
    alignItems: "center",
    gap: 14,
    maxWidth: 380,
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0,0,0,0.06)",
    transition: "box-shadow 0.2s ease, transform 0.2s ease",
  },
  workspaceItemHover: {
    boxShadow: "0 6px 20px rgba(0,0,0,0.1)",
    transform: "translateX(4px)",
  },
  workspaceAvatar: {
    width: 46,
    height: 46,
    background: "linear-gradient(135deg, #f0a020, #e07010)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    flexShrink: 0,
    boxShadow: "0 3px 8px rgba(240,160,32,0.35)",
  },
  workspaceInitial: { fontSize: 20, fontWeight: 800, color: "#fff", lineHeight: 1 },
  workspaceHomeIcon: {
    position: "absolute", bottom: -4, right: -4, background: "#fff",
    borderRadius: 4, padding: 2, color: "#333", display: "flex",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)", transform: "scale(0.72)",
  },
  workspaceName: { fontWeight: 600, fontSize: 14, color: "#1a1a1a", letterSpacing: "-0.1px" },
  workspaceOrg: { fontSize: 12, color: "#999", marginTop: 2, fontWeight: 400 },
  workspaceList: { display: "flex", flexDirection: "column", gap: 10 },
  // ── New Workspace Button (small elegant) ─────
  newWorkspaceBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    background: "#fff",
    border: "1px solid #e2e2e2",
    borderRadius: 8,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#777",
    cursor: "pointer",
    boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
    transition: "all 0.18s ease",
    letterSpacing: "0.1px",
    marginTop: 2,
  },
  newWorkspaceBtnHover: {
    background: "#2bbdcc",
    borderColor: "#2bbdcc",
    color: "#fff",
    boxShadow: "0 3px 12px rgba(43,189,204,0.3)",
    transform: "translateY(-1px)",
  },
  // ── Empty State ──────────────────────────────
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 20px",
    background: "#fff",
    borderRadius: 12,
    border: "1.5px dashed #e0e0e0",
    maxWidth: 380,
    gap: 8,
  },
  emptyIcon: { fontSize: 28, lineHeight: 1 },
  emptyText: { fontSize: 13, color: "#bbb", fontWeight: 400, margin: 0 },
};

export default styles;